# Exploratory Database Queries in Python

## Import Modules and Connect to Database

In [1]:
import pandas as pd
import sqlite3 as sql

In [2]:
con = sql.connect('teca.db')

## Get the Database Schema

In [3]:
df = pd.read_sql('SELECT * FROM sqlite_master WHERE type="table";', con)
df = df.set_index('name')
df

,type,tbl_name,rootpage,sql
name,,,,
parents,table,parents,2,CREATE TABLE parents \n (parent...
categories,table,categories,4,CREATE TABLE categories \n (cat...
products,table,products,8,CREATE TABLE products \n (produ...
customers,table,customers,137,CREATE TABLE customers \n (cust...
sites,table,sites,1528,CREATE TABLE sites \n (site_id ...
transactions,table,transactions,1534,CREATE TABLE transactions\n (unique_id ...

## Table Overview

### Column Names, Types, and Relationships

In [4]:
print(df.loc['transactions', 'sql'])

CREATE TABLE transactions
        (unique_id INT PRIMARY KEY,
        transaction_id TEXT NOT NULL,
        unformatted_date TEXT NOT NULL,
        customer_id TEXT,
        product_id TEXT,
        site_id TEXT,
        revenue REAL,
        costs REAL,
        units INT,
        FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
        FOREIGN KEY (site_id) REFERENCES sites(site_id),
        FOREIGN KEY (product_id) REFERENCES products(product_id))

### Number of Rows

In [5]:
pd.read_sql('SELECT COUNT(*) FROM transactions;', con)

   COUNT(*)
0   1050000

### First Five Rows

In [6]:
pd.read_sql('SELECT * FROM transactions LIMIT 5;', con)

,unique_id,transaction_id,unformatted_date,customer_id,product_id,site_id,revenue,costs,units
0,1161545,20240417|433|2|1|4888093,2024-07-11,nan,3437,197,1.69,1.18000,1
1,324500,20230507|361|1|2|2198879,2023-07-31,nan,6509,131,11.96,7.00000,4
2,2389914,20250904|667|3|1|6216813,2025-11-28,5362.03,18234,336,-5.00,0.00000,5
3,1441536,20230727|562|2|2|3827487,2023-10-20,nan,9055,297,1.00,0.95000,1
4,1269552,20250209|497|2|2|3338196,2025-05-05,7795.258,10299,257,2.79,1.38333,1

### Number of Missing Values

In [8]:
pd.read_sql('SELECT COUNT(*) FROM transactions WHERE customer_id IS "nan";', con)

   COUNT(*)
0    782896

## Read in the Data for Analysis

In [9]:
query = '''
SELECT *
FROM transactions
WHERE revenue > 2;
'''
df = pd.read_sql(query, con)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 570874 entries, 0 to 570873
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   unique_id         570874 non-null  int64
 1   transaction_id    570874 non-null  object
 2   unformatted_date  570874 non-null  object
 3   customer_id       570874 non-null  object
 4   product_id        570874 non-null  object
 5   site_id           570874 non-null  object
 6   revenue           570874 non-null  float64
 7   costs             570746 non-null  float64
 8   units             570856 non-null  float64
dtypes: float64(3), int64(1), object(5)
memory usage: 39.2+ MB

In [10]:
con.close()