# Connecting and Disconnecting to a Database

## 1. Connecting and Disconnecting to a SQLite Database

In [1]:
import pandas as pd
import sqlite3 as sql
con = sql.connect('teca.db')

In [2]:
pd.read_sql('SELECT * FROM parents LIMIT 5;', con)

   parent_id          parent_name
0          5         Salty Snacks
1        140            Ice Cream
2        307  Store Services (92)
3        175        Lottery (360)
4        215      Energy non-carb

In [3]:
pd.read_sql('SELECT * FROM sites LIMIT 5;', con)

,site_id,site_name,address,city,zip,latitude,longitude,site_status
0,197,433 Bay Minette,701 Mcmeans Ave,Bay Minette,36507,40.1474,-92.3793,ACTIVE
1,131,361 Oakdale,500 Hohman St,Oakdale,68761,42.0694,-97.9698,ACTIVE
2,336,667 Hooper,11701 State Highway 17,Hooper,81136,37.7451,-105.8810,ACTIVE
3,297,562 Columbia,101 S Providence Rd,Columbia,65203,38.9509,-92.3362,ACTIVE
4,257,497 Patton,1000 State Route 51,Patton,63662,37.5003,-90.0134,ACTIVE

In [4]:
con.close()

In [5]:
pd.read_sql('SELECT * FROM categories LIMIT 5;', con)

ProgrammingError: Cannot operate on a closed database.

## 2. Connecting and Disconnecting with a Context Manager 

When you're not exploring the data, then this approach is best.

In [6]:
with sql.connect('teca.db') as con:
    df = pd.read_sql('SELECT * FROM categories LIMIT 5;', con)
df

   category_id                         category_name  parent_id
0           53   Salty Snacks -tort/corn Chips (152)          5
1           39             Ice Cream-novelties (124)        140
2          135                     Lottery-win (270)        307
3          138  Gaming-lottery (scratch Tickt) (272)        175
4          142              Energy non-carb FS (279)        215

## 3. Connecting to Different RDBMSs

In [ ]:
# MySQL connection
import mysql.connector # pip install mysql-connector

con = mysql.connector.connect(user='<username>', 
                              password='<password>',
                              host='<url>',
                              database='<database name>')

In [ ]:
# Microsoft SQL Server
import pyodbc # pip install pyodbc

conn_str = (
    r'DRIVER={SQL Server};'
    r'SERVER=<server name>;'
    r'DATABASE=<database name>;'
    r'UID=<username>;'
    r'PWD=<password>'
)
con = pyodbc.connect(conn_str)