# SQL Join Queries in Python

## Import Modules and Connect to Database

In [1]:
import pandas as pd
import sqlite3 as sql

In [2]:
con = sql.connect('teca.db')

## Get the Database Schema

In [3]:
df = pd.read_sql('SELECT * FROM sqlite_master WHERE type="table";', con)
df = df.set_index('name')
df

,type,tbl_name,rootpage,sql
name,,,,
parents,table,parents,2,CREATE TABLE parents \n (parent...
categories,table,categories,4,CREATE TABLE categories \n (cat...
products,table,products,8,CREATE TABLE products \n (produ...
customers,table,customers,137,CREATE TABLE customers \n (cust...
sites,table,sites,1528,CREATE TABLE sites \n (site_id ...
transactions,table,transactions,1534,CREATE TABLE transactions\n (unique_id ...

In [4]:
print(df.loc['transactions', 'sql'])

CREATE TABLE transactions
        (unique_id INT PRIMARY KEY,
        transaction_id TEXT NOT NULL,
        unformatted_date TEXT NOT NULL,
        customer_id TEXT,
        product_id TEXT,
        site_id TEXT,
        revenue REAL,
        costs REAL,
        units INT,
        FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
        FOREIGN KEY (site_id) REFERENCES sites(site_id),
        FOREIGN KEY (product_id) REFERENCES products(product_id))

In [5]:
print(df.loc['sites', 'sql'])

CREATE TABLE sites
                (site_id TEXT PRIMARY KEY,
                site_name TEXT,
                address TEXT,
                city TEXT,
                zip INT,
                latitude REAL,
                longitude REAL,
                site_status TEXT)

## Left Join

In [7]:
query = '''
SELECT t.revenue, t.costs, t.units, s.site_name
FROM transactions AS t
LEFT JOIN sites as s
ON t.site_id=s.site_id;
'''
df = pd.read_sql(query, con)
df

         revenue    costs  units           site_name
0           1.69  1.18000    1.0     433 Bay Minette
1          11.96  7.00000    4.0         361 Oakdale
2          -5.00  0.00000    5.0          667 Hooper
3           1.00  0.95000    1.0        562 Columbia
4           2.79  1.38333    1.0          497 Patton
...          ...      ...    ...                 ...
1049995     7.15  5.80091    1.0     28 Sioux Rapids
1049996     1.89  1.12000    1.0         362 Norfork
1049997     4.49  1.70400    1.0  2926 Commerce City
1049998     1.99  0.78500    1.0        520 Atlantic
1049999     3.49  1.93786    1.0          667 Hooper

[1050000 rows x 4 columns]

In [10]:
query = '''
SELECT t.revenue, t.costs, t.units, s.site_name
FROM transactions AS t
LEFT JOIN sites as s
ON t.site_id=s.site_id 
WHERE site_name = "433 Bay Minette" 
ORDER BY revenue DESC;
'''
df = pd.read_sql(query, con)
df

      revenue     costs    units        site_name
0      125.00  111.1061   46.313  433 Bay Minette
1      120.58  107.3242   44.186  433 Bay Minette
2      119.00  107.4803   38.399  433 Bay Minette
3      101.00   90.7601   34.133  433 Bay Minette
4      100.00    0.0000    1.000  433 Bay Minette
...       ...       ...      ...              ...
8446  -100.00    0.0000  100.000  433 Bay Minette
8447  -100.00    0.0000  100.000  433 Bay Minette
8448  -104.00    0.0000  104.000  433 Bay Minette
8449  -150.00    0.0000   -1.000  433 Bay Minette
8450  -200.00    0.0000  200.000  433 Bay Minette

[8451 rows x 4 columns]

In [11]:
query = '''
SELECT t.revenue, t.costs, t.units, s.site_name, p.product_name
FROM transactions AS t
LEFT JOIN sites as s
ON t.site_id=s.site_id
LEFT JOIN products as p
ON t.product_id=p.product_id;
'''
df = pd.read_sql(query, con)
df

,revenue,costs,units,site_name,product_name
0,1.69,1.18000,1.0,433 Bay Minette,DORITO SMPLY WHT CHDDR 2.5OZ
1,11.96,7.00000,4.0,361 Oakdale,NESTLE TH VNL SAND 6OZ
2,-5.00,0.00000,5.0,667 Hooper,LOTTERY WIN
3,1.00,0.95000,1.0,562 Columbia,MO HAPPY CAMPER 158
4,2.79,1.38333,1.0,497 Patton,MONSTER REHAB ORNGADE 15.5OZ
...,...,...,...,...,...
1049995,7.15,5.80091,1.0,28 Sioux Rapids,CAMEL TK RYL 85 BX
1049996,1.89,1.12000,1.0,362 Norfork,MM ORNG 15.2OZ
1049997,4.49,1.70400,1.0,2926 Commerce City,SUB RST BEEF CHDR FCS
1049998,1.99,0.78500,1.0,520 Atlantic,HOSTESS HOHO 3OZ 3CT
1049999,3.49,1.93786,1.0,667 Hooper,NAKED JC BLU SMTHIE 15.2OZ

In [12]:
con.close()